### ISSUE TITLE
启动报错：No such file or diractory

### ISSUE THREAD

**Issue by mhmzx** [RanKKI/BangumiBot#16]
我确定我设置的几个目录都是存在的，请问问题出在哪里呢？谢谢！

启动日志如下：

```
(.venv) madray@nas-ubuntu-2204:~/BangumiBot$ uvicorn main:app --host 0.0.0.0:8085 --log-config ./conf/log.yml
2022-11-23 13:59:35 - [INFO] - QBitTorrent Connecting to 127.0.0.1:8082
2022-11-23 13:59:35 - [INFO] - Started server process [182694]
2022-11-23 13:59:35 - [INFO] - Waiting for application startup.
2022-11-23 13:59:35 - [INFO] - Connecting to Redis...
2022-11-23 13:59:35 - [INFO] - Connected to Redis, version 7.0.5
2022-11-23 13:59:36 - [INFO] - qBittorrent: v4.4.5.10
2022-11-23 13:59:36 - [INFO] - qBittorrent Web API: 2.8.5
2022-11-23 13:59:36 - [INFO] - Starting...
2022-11-23 13:59:36 - [INFO] - Application startup complete.
Exception in thread Thread-2:
2022-11-23 13:59:36 - [INFO] - Env
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2022-11-23 13:59:36 - [ERRO] - [Errno -2] Name or service not known
    self.run()
  File "/home/madray/BangumiBot/./bangumi/manager/config.py", line 33, in run
2022-11-23 13:59:36 - [INFO] - -----------  ------------------------------------------
2022-11-23 13:59:36 - [INFO] - Waiting for application shutdown.
2022-11-23 13:59:36 - [INFO] - Log Level    INFO
    self.observer.start()
2022-11-23 13:59:36 - [INFO] - Application shutdown complete.
  File "/home/madray/BangumiBot/.venv/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
2022-11-23 13:59:36 - [INFO] - Client       qbittorrent
2022-11-23 13:59:36 - [INFO] - Client Addr  ...@127.0.0.1:8082
2022-11-23 13:59:36 - [INFO] - Redis        @127.0.0.1:6379
2022-11-23 13:59:36 - [INFO] - Check        600
2022-11-23 13:59:36 - [INFO] - Download     /mnt/sda1/Downloads/bangumi
2022-11-23 13:59:36 - [INFO] - Cache        ./.cache
2022-11-23 13:59:36 - [INFO] - Media        /mnt/sda1/OneDrive - sgpublic/公开资源/Bangumi
2022-11-23 13:59:36 - [INFO] - Config       ./.config
2022-11-23 13:59:36 - [INFO] - Seeding      True
2022-11-23 13:59:36 - [INFO] - 
    emitter.start()
  File "/home/madray/BangumiBot/.venv/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/home/madray/BangumiBot/.venv/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/madray/BangumiBot/.venv/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/madray/BangumiBot/.venv/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 169, in __init__
    self._add_watch(path, event_mask)
  File "/home/madray/BangumiBot/.venv/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/home/madray/BangumiBot/.venv/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 406, in _raise_error
    raise OSError(err, os.strerror(err))
FileNotFoundError: [Errno 2] No such file or directory
```

<details>
<summary>rss.json</summary>

```json
{
    "urls": [
        "https://mikanani.me/RSS/MyBangumi?token=..."
    ],
    "rules": [
        ".*简.*"
    ],
    "parsers": [

    ],
    "mapper": [

    ]
}
```
</details>

<details>
<summary>notification.json</summary>

```json
[

]
```
</details>

<details>
<summary>.env</summary>

```
# Client Type: [aria2, qbittorrent, transmission]
BANGUMI_CLIENT_TYPE = "qbittorrent"

# Client Setting
BANGUMI_CLIENT_IP = "127.0.0.1"
BANGUMI_CLIENT_PORT = 8082
BANGUMI_CLIENT_USERNAME = "..."
BANGUMI_CLIENT_PASSWORD = "..."

# Redis
BANGUMI_REDIS_HOST = "127.0.0.1"
BANGUMI_REDIS_PORT = 6379
BANGUMI_REDIS_PASSWORD = ""

# Folder
BANGUMI_DOWNLOAD_FOLDER = "/mnt/sda1/Downloads/bangumi"
BANGUMI_CACHE_FOLDER = "./.cache"
BANGUMI_MEDIA_FOLDER = "/mnt/sda1/OneDrive - sgpublic/公开资源/Bangumi"

# RSS Setting
BANGUMI_CHECK_INTERVAL = 600 # 60 * 10 分钟检查一次

# Config Setting
BANGUMI_CONFIG_PATH = "./.config"

# Logger Setting
BANGUMI_LOGGER_LEVEL = "INFO"

BANGUMI_SEEDING = 1
```
</details>

**Comment by RanKKI** [comment]
🤦 手滑打错了，这就去改
